Eric Sunshine fixed several problems recently introduced into csLoadLibrary() in OSXDynamicLibrary.cpp:
-*- Compilation error: Incoming argument did not match variable name used
    in code.

-*- Run-time failure: Was using a lot of hard-coded constants for path
    dissection, but the constants were incorrect.

-*- Memory trashing: Was not allocating sufficient memory for the working
    path buffer, thus corrupting memory beyond end of buffer.

-*- Memory leak: Was leaking the working buffer.